package dart

import (
	"os"
	"path/filepath"
	"testing"
)

// ---------------------------------------------------------------------------
// Lockfile parser tests
// ---------------------------------------------------------------------------

func TestLoadPubspecLock(t *testing.T) {
	dir := t.TempDir()

	lockContent := `# Generated by pub
packages:
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04fbf07a0853e911c4f60b145db25e24f4e87571"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "a2bbf9d017fcefaa86a23c9f7f4ad0f561bc4f12"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  collection:
    dependency: "direct dev"
    description:
      name: collection
    source: hosted
    version: "1.18.0"
  async:
    dependency: transitive
    description:
      name: async
    source: hosted
    version: "2.11.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	if err := os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadPubspecLock(dir)
	if err != nil {
		t.Fatalf("loadPubspecLock: %v", err)
	}

	byName := make(map[string]DartPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	// http is a direct main dep.
	if _, ok := byName["http"]; !ok {
		t.Error("expected 'http' in packages")
	}
	if byName["http"].Version != "1.2.1" {
		t.Errorf("http version: got %q, want %q", byName["http"].Version, "1.2.1")
	}
	if !byName["http"].Direct {
		t.Error("http should be a direct dep")
	}

	// collection is a direct dev dep.
	if _, ok := byName["collection"]; !ok {
		t.Error("expected 'collection' in packages")
	}
	if !byName["collection"].Direct {
		t.Error("collection should be a direct dep")
	}

	// characters is transitive.
	if _, ok := byName["characters"]; !ok {
		t.Error("expected 'characters' in packages")
	}
	if byName["characters"].Direct {
		t.Error("characters should not be a direct dep")
	}
	if byName["characters"].Version != "1.3.0" {
		t.Errorf("characters version: got %q, want %q", byName["characters"].Version, "1.3.0")
	}

	// async is transitive.
	if byName["async"].Direct {
		t.Error("async should not be a direct dep")
	}
}

func TestLoadPubspecYAML(t *testing.T) {
	dir := t.TempDir()

	content := `name: my_app
description: A Flutter application.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  dio: ^5.0.0
  path_provider: "^2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
`
	if err := os.WriteFile(filepath.Join(dir, "pubspec.yaml"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadPubspecYAML(dir)
	if err != nil {
		t.Fatalf("loadPubspecYAML: %v", err)
	}

	byName := make(map[string]DartPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	if _, ok := byName["http"]; !ok {
		t.Error("expected 'http' in packages")
	}
	if _, ok := byName["dio"]; !ok {
		t.Error("expected 'dio' in packages")
	}
	if _, ok := byName["path_provider"]; !ok {
		t.Error("expected 'path_provider' in packages")
	}
	if _, ok := byName["flutter_lints"]; !ok {
		t.Error("expected 'flutter_lints' in packages")
	}
	// All should be direct.
	for _, p := range pkgs {
		if !p.Direct {
			t.Errorf("package %q should be Direct=true in pubspec.yaml parse", p.Name)
		}
	}
	// sdk entries like "flutter" should be skipped.
	if _, ok := byName["sdk"]; ok {
		t.Error("sdk key should not appear as a package")
	}
}

func TestLoadEmptyDir(t *testing.T) {
	dir := t.TempDir()
	_, err := Load(dir)
	if err == nil {
		t.Error("expected error for directory with no Dart lockfiles")
	}
}

func TestLoadPubspecLockEmpty(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte{}, 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPubspecLock(dir)
	if err != nil {
		t.Fatalf("loadPubspecLock() unexpected error for empty file: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for empty pubspec.lock, got %d", len(pkgs))
	}
}

func TestLoadPubspecYAMLEmpty(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "pubspec.yaml"), []byte{}, 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPubspecYAML(dir)
	if err != nil {
		t.Fatalf("loadPubspecYAML() unexpected error for empty file: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for empty pubspec.yaml, got %d", len(pkgs))
	}
}

// ---------------------------------------------------------------------------
// Capability detection tests
// ---------------------------------------------------------------------------

func TestDetectCapabilities(t *testing.T) {
	dir := t.TempDir()
	src := `import 'dart:io';
import 'package:http/http.dart';

void main() {
  // Read a file
  final f = File('config.txt');
  // Run a process
  Process.run('ls', ['-la']);
}
`
	if err := os.WriteFile(filepath.Join(dir, "main.dart"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)

	wantCaps := []string{"fs:read", "fs:write", "exec", "network"}
	for _, want := range wantCaps {
		if !caps.Has(want) {
			t.Errorf("expected capability %q to be detected", want)
		}
	}
}

func TestDetectNoCapabilities(t *testing.T) {
	dir := t.TempDir()
	src := `/// A simple utility library with no I/O.
int add(int a, int b) => a + b;

String greet(String name) => 'Hello, $name!';
`
	if err := os.WriteFile(filepath.Join(dir, "utils.dart"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)
	if !caps.IsEmpty() {
		t.Errorf("expected no capabilities for benign code, got: %v", caps.List())
	}
}

func TestDetectDartImportVariants(t *testing.T) {
	dir := t.TempDir()
	src := `import "dart:mirrors";
import 'dart:ffi';
import "package:ffi/ffi.dart";
`
	if err := os.WriteFile(filepath.Join(dir, "reflection.dart"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)
	if !caps.Has("reflect") {
		t.Error("expected 'reflect' capability from dart:mirrors import")
	}
	if !caps.Has("unsafe") {
		t.Error("expected 'unsafe' capability from dart:ffi / ffi imports")
	}
}

// ---------------------------------------------------------------------------
// Adapter integration tests
// ---------------------------------------------------------------------------

func TestAdapterName(t *testing.T) {
	a := Adapter{}
	if a.Name() != "dart" {
		t.Errorf("Name() = %q, want %q", a.Name(), "dart")
	}
}

func TestAdapterLoad(t *testing.T) {
	dir := t.TempDir()

	lockContent := `# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
    source: hosted
    version: "1.2.1"
  async:
    dependency: transitive
    description:
      name: async
    source: hosted
    version: "2.11.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	if err := os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o600); err != nil {
		t.Fatal(err)
	}

	a := Adapter{}
	g, err := a.Load(dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if g == nil {
		t.Fatal("Load returned nil graph")
	}

	if len(g.Modules) < 2 {
		t.Errorf("expected at least 2 modules, got %d", len(g.Modules))
	}

	if _, ok := g.Packages["http"]; !ok {
		t.Error("expected 'http' package in graph")
	}
	if _, ok := g.Packages["async"]; !ok {
		t.Error("expected 'async' package in graph")
	}

	// http is direct, so root should have an edge to it.
	rootName := filepath.Base(dir)
	rootEdges := g.Edges[rootName]
	foundHTTP := false
	for _, e := range rootEdges {
		if e == "http" {
			foundHTTP = true
		}
	}
	if !foundHTTP {
		t.Error("root should have edge to direct dep 'http'")
	}
}

// ---------------------------------------------------------------------------
// Fuzz test
// ---------------------------------------------------------------------------

func FuzzParsePubspecLock(f *testing.F) {
	f.Add([]byte("# Generated by pub\npackages:\n  http:\n    dependency: \"direct main\"\n    version: \"1.2.1\"\n"))
	f.Add([]byte(""))
	f.Add([]byte("# comment only"))
	f.Add([]byte("packages:\n"))
	f.Add([]byte("sdks:\n  dart: \">=3.0.0 <4.0.0\"\n"))

	f.Fuzz(func(t *testing.T, data []byte) {
		defer func() { recover() }() //nolint:errcheck

		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "pubspec.lock"), data, 0o600); err != nil {
			return
		}
		loadPubspecLock(dir) //nolint:errcheck
	})
}
